#!/bin/bash

export SONIC_MGMT_ROOT=/usr/sonic-mgmt
export SONIC_CLI_ROOT=$SONIC_MGMT_ROOT/sonic-cli
export SYSTEM_NAME="${HOSTNAME%%.*}"
export PYTHONPATH=$SONIC_MGMT_ROOT/:$PYTHONPATH
export CLISH_PATH=$SONIC_CLI_ROOT/target/sonic-cli-xml
export LD_LIBRARY_PATH=$SONIC_MGMT_ROOT/lib:$LD_LIBRARY_PATH
export PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin:$SONIC_CLI_ROOT/target

clish
